language: rust
cache: cargo
dist: trusty

os:
  - linux
  - osx

rust:
  - stable

addons:
  apt:
    packages:
      - gtk+-3.0
      - glib-2.0

env:
  global:
    - LD_LIBRARY_PATH=/usr/local/lib
  matrix:
    - SUITE=apu_tests
    - SUITE=cpu_tests
    - SUITE=ppu_tests

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install portaudio; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install pkg-config; fi

script:
  - cargo build --release
  - cargo test --release --test $SUITE