language: rust
cache: cargo
dist: trusty

os:
  - linux
  - osx

rust:
  - stable

addons:
  apt:
    packages:
      - gtk+-3.0
      - glib-2.0

env:
    - LD_LIBRARY_PATH=/usr/local/lib

install:
    - curl -O http://www.portaudio.com/archives/pa_stable_v19_20140130.tgz
    - tar xfz pa_stable_v19_20140130.tgz
    - (cd portaudio/ && ./configure && make && sudo make install)

script:
  - cargo build
  - cargo test