name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: nightly
      - name: Build
        run: cargo build --verbose --release
      - name: Run integration tests
        run: cargo test --package emu --features test --release
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          name: emu-linux
          path: target/release/emu

  build-win:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: nightly
      - name: Build
        run: cargo build --verbose --release
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          name: emu-win.exe
          path: target/release/emu-win.exe

  build-mac:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: nightly
      - name: Build
        run: cargo build --verbose --release
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          name: emu-mac
          path: target/release/emu
